apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
spec:
  serviceName: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
          image: {{ .Values.database.image }}:{{ .Values.database.imageTag }}
          ports:
            - containerPort: {{ .Values.database.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.applicationName }}-{{ .Values.branchName }}
            - secretRef:
                name: {{ .Values.applicationName }}-{{ .Values.branchName }}
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
              mountPath: /var/lib/mysql
            - name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-data-sql
              mountPath: /etc/mysql/conf.d/30-data.sql
              subPath: 30-data.sql
            - name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-schema-sql
              mountPath: /etc/mysql/conf.d/20-schema.sql
              subPath: 20-schema.sql
            - name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-user-sql
              mountPath: /etc/mysql/conf.d/10-user.sql
              subPath: 10-user.sql
      volumes:
        - configMap:
            name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-user-sql
          name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-user-sql
        - configMap:
            name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-data-sql
          name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-data-sql
        - configMap:
            name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-schema-sql
          name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-schema-sql

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.database.storage }}
