apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-user-sql
data:
  10-user.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.config.databaseName }};

    ALTER DATABASE {{ .Values.config.databaseName }}
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

    CREATE USER IF NOT EXISTS 'petclinic'@'%' IDENTIFIED BY 'Insecure';

    GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%';

    FLUSH PRIVILEGES;
