apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-{{ .Values.branchName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-{{ .Values.branchName }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.applicationName }}-{{ .Values.branchName }}
          image: nginx:alpine
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
