apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-init
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /bin/sh
            - -c
            - "mysql -h {{ .Values.database.host }} -P {{ .Values.database.port }} -u ${SPRING_DATASOURCE_USERNAME} -p${SPRING_DATASOURCE_PASSWORD} < /etc/mysql/init/10-init.sql"
          envFrom:
            - configMapRef:
                name: {{ .Values.applicationName }}-{{ .Values.branchName }}
            - secretRef:
                name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
          image: mysql:9.3
          name: db-init
          volumeMounts:
            - mountPath: /etc/mysql/init/10-init.sql
              name: db-init
              readOnly: true
              subPath: 10-init.sql
      restartPolicy: OnFailure
      volumes:
        - configMap:
            name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-init
          name: db-init
