apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
  labels:
    app: {{ .Values.applicationName }}-{{ .Values.branchName }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}
  storageClassName: {{ .Values.database.storageClass }}
