apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}
data:
  MYSQL_DATABASE: {{ .Values.config.databaseName }}
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Values.applicationName }}-{{ .Values.branchName }}-db:{{ .Values.database.containerPort }}/{{ .Values.config.databaseName }}?useUnicode=true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.springJpaDdlHibernateAuto }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive }}
