apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-{{ .Values.branchName }}-db-user-sql
data:
  user.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.config.databaseName }};

    ALTER DATABASE {{ .Values.config.databaseName }}
      DEFAULT CHARACTER SET utf8
      DEFAULT COLLATE utf8_general_ci;

    GRANT ALL PRIVILEGES ON {{ .Values.config.databaseName }}.* TO '{{ .Values.secret.mysqlUser }}'@'%' IDENTIFIED BY '{{ .Values.secret.mysqlPassword }}';
