pipeline {
  agent none
  environment {
    AGENT_IMAGE = 'shykin/alpine:d1a05482c9cd4403cfa693719c3c57a77113cfcb'
    DOCKER_HOST_ = 'tcp://172.31.18.232:2375'
    APP_NAME = 'spring-petclinic'
    AWS_ACCOUNT_ID = "${AWS_ACCOUNT_ID_}"
    AWS_REGION = 'eu-north-1'
    IMAGE_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    AWS_CRED_ID='jenkins-aws'
  }
  stages {
    stage('Build App') {
      options {
        timeout(time: 600, unit: 'SECONDS')
      }
      when {
        allOf {
          anyOf {
            changeset "src/main/**"
            triggeredBy 'UserIdCause'
          }
          expression {
            env.BRANCH_NAME in ['main', 'test']
          }
        }
      }
      agent {
        dockerContainer {
          image "${AGENT_IMAGE}"
        }
      }
      steps {
        sh 'mvn -B package'
        stash includes: '**/target/*.jar', name: 'package'
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
        }
      }
    }
stage('Build Image') {
      options {
        timeout(time: 600, unit: 'SECONDS')
      }
      when {
        allOf {
          anyOf {
            changeset "src/main/**"
            triggeredBy 'UserIdCause'
          }
          expression {
            env.BRANCH_NAME in ['main', 'test']
          }
        }
      }
      agent {
        dockerContainer {
          image "${AGENT_IMAGE}"
        }
      }
      environment {
        DOCKER_HOST = "${DOCKER_HOST_}"
      }
      steps {
        withCredentials([usernamePassword(credentialsId: AWS_CRED_ID, usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          unstash 'package'
          sh 'cp target/*.jar app.jar'
          sh 'cp cicd/Dockerfile .'
          sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com'
          sh 'docker buildx build -t $GIT_COMMIT .'
          sh 'docker tag $GIT_COMMIT $IMAGE_REGISTRY/$APP_NAME-$BRANCH_NAME:$GIT_COMMIT'
          sh 'docker push $IMAGE_REGISTRY/$APP_NAME-$BRANCH_NAME:$GIT_COMMIT'
          sh 'docker image rm $GIT_COMMIT $IMAGE_REGISTRY/$APP_NAME-$BRANCH_NAME:$GIT_COMMIT'
          sh 'docker logout'
          archiveArtifacts artifacts: 'metadata.json', fingerprint: true
        }
      }
    }
  }
}
