pipeline {
  agent none
  environment {
    APP_NAME = 'spring-petclinic'
    DOCKER_HOST = 'https://172.31.18.232:2375'
    REGISTRY_SECRET_ID = 'dockerhub'
  }
  stages {
    stage('Build App') {
      options {
        timeout(time: 300, unit: 'SECONDS')
      }
      when {
        allOf {
          anyOf {
            changeset "src/main/**"
            triggeredBy 'UserIdCause'
          }
          expression {
            env.BRANCH_NAME in ['main', 'test']
          }
        }
      }
      agent {
        dockerContainer {
          image 'shykin/alpine:4f5d8d5570d3e29e68d4a5c8e77c532607009f7a'
        }
      }
      steps {
        sh 'mvn -B package'
        stash includes: '**/target/*.jar', name: 'package'
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
        }
      }
    }
stage('Build Image') {
      options {
        timeout(time: 300, unit: 'SECONDS')
      }
      when {
        allOf {
          anyOf {
            changeset "src/main/**"
            triggeredBy 'UserIdCause'
          }
          expression {
            env.BRANCH_NAME in ['main', 'test']
          }
        }
      }
      agent {
        dockerContainer {
          image 'shykin/alpine:4f5d8d5570d3e29e68d4a5c8e77c532607009f7a'
        }
      }
      steps {
        withCredentials([usernamePassword(credentialsId: REGISTRY_SECRET_ID, usernameVariable: 'REGISTRY_USER', passwordVariable: 'REGISTRY_PASSWORD')]) {
          unstash 'package'
          sh 'echo "{\\\"auths\\\":{\\\"$IMAGE_REGISTRY\\\":{\\\"auth\\\":\\\"$(echo -n $REGISTRY_USER:$REGISTRY_PASSWORD | base64)\\\"}}}" > /kaniko/.docker/config.json'
          sh 'cp target/*.jar ./app.jar'
          sh 'docker build -t $REGISTRY_USER/$APP_NAME-$BRANCH_NAME:$GIT_COMMIT .'
          archiveArtifacts artifacts: 'image.txt', fingerprint: true
        }
      }
    }
  }
}
